### ISSUE TITLE
Is there any way to sync cache when mongodb is updated

### ISSUE THREAD

**Issue by elaijuh** [Clever/moredis#20]
I want to query with the last updated time per mongodb document and update the value of the key in redis, seems current design has no way to do that

Is it possible to add `RefreshCache` in addition to `BuildCache` ?

**Comment by mohit** [comment]
@elaijuh We don't plan on adding support since it requires that data in the MongoDB collection is specifically designed to support the `Refresh`. Internally, in the past we have relied on dialing the [MongoDB Oplog](https://github.com/Clever/ARCHIVED-mgotail) to ensure that we are keeping track of changes in mongo.

Of course you are welcome to submit a PR and I'm sure we can merge this as an optional feature :).
